# Taps
tap 'homebrew/cask'
tap 'homebrew/bundle'
tap 'koekeishiya/formulae' 		# yabai
tap 'jesseduffield/lazygit' 	# lazygit
tap 'stripe/stripe-cli' 		  # stripe-cli
tap 'nicoverbruggen/homebrew-cask'

# Brew
brew 'ffmpeg'
brew 'fzf'
brew 'git'
brew 'gh'
brew 'httpie'
brew 'mycli'
brew 'mysql-client'
brew 'python@3.9'
brew 'sqlite'
brew 'tmux'
brew 'neovim'
brew 'youtube-dl'
brew 'zsh-autosuggestions'
brew 'lazygit'
brew 'trash'
brew 'bat'
brew 'rg'
brew 'yabai'
brew 'watch'
brew 'legit'
brew 'pure'
brew 'stripe'
brew 'node@16' # Need v16 for intelephense to work
brew 'nginx'
brew 'php'
brew 'dnsmasq'
brew 'btop'
brew 'starship'
brew 'difftastic'
brew 'jq'
brew 'iperf3'

# Cask
cask 'firefox'
cask 'karabiner-elements'
cask 'slack'
cask 'telegram'
cask 'discord'
cask 'imageoptim'
cask '1password'
cask 'tinkerwell'
cask 'tableplus'
cask 'helo'
cask 'ray'
cask 'invoker'
cask 'docker'
cask 'phpmon'
cask '1password/tap/1password-cli'
